<?php

namespace SMS\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * pageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pageRepository extends EntityRepository
{
}
