liens_index:
    path:     /
    defaults: { _controller: "SMSAdminBundle:Liens:index" }
    methods:  GET

liens_show:
    path:     /{id}/show
    defaults: { _controller: "SMSAdminBundle:Liens:show" }
    methods:  GET

liens_new:
    path:     /new
    defaults: { _controller: "SMSAdminBundle:Liens:new" }
    methods:  [GET, POST]

liens_edit:
    path:     /{id}/edit
    defaults: { _controller: "SMSAdminBundle:Liens:edit" }
    methods:  [GET, POST]

liens_delete:
    path:     /{id}/delete
    defaults: { _controller: "SMSAdminBundle:Liens:delete" }
    methods:  DELETE
