page_index:
    path:     /
    defaults: { _controller: "SMSAdminBundle:page:index" }
    methods:  GET

page_show:
    path:     /{id}/show
    defaults: { _controller: "SMSAdminBundle:page:show" }
    methods:  GET

page_new:
    path:     /new
    defaults: { _controller: "SMSAdminBundle:page:new" }
    methods:  [GET, POST]

page_edit:
    path:     /{id}/edit
    defaults: { _controller: "SMSAdminBundle:page:edit" }
    methods:  [GET, POST]

page_delete:
    path:     /{id}/delete
    defaults: { _controller: "SMSAdminBundle:page:delete" }
    methods:  DELETE
