sms_commune:
    resource: "@SMSCommuneBundle/Resources/config/routing.yml"
    prefix:   /
 
sms_admin_langue:
    resource: "@SMSAdminBundle/Resources/config/routing/langue.yml"
    prefix:   /langue
    
sms_admin_categorie:
    resource: "@SMSAdminBundle/Resources/config/routing/categorie.yml"
    prefix:   /categorie

sms_admin_liens:
    resource: "@SMSAdminBundle/Resources/config/routing/liens.yml"
    prefix:   /liens
    
sms_admin_block:
    resource: "@SMSAdminBundle/Resources/config/routing/block.yml"
    prefix:   /block
    
sms_admin_accueil:
    resource: "@SMSAdminBundle/Resources/config/routing/accueil.yml"
    prefix:   /accueil  

sms_admin_bloc:
    resource: "@SMSAdminBundle/Resources/config/routing/bloc.yml"
    prefix:   /bloc
    
sms_admin_menu:
    resource: "@SMSAdminBundle/Resources/config/routing/menu.yml"
    prefix:   /menu

sms_admin_page:
    resource: "@SMSAdminBundle/Resources/config/routing/page.yml"
    prefix:   /page
    
sms_commune_fr:
    resource: "@SMSCommuneBundle/Resources/config/fr.yml"
    prefix:   /fr

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin
 
sonata_user_security:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"

sonata_user_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
    prefix: /resetting

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix: /profile

sonata_user_register:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
    prefix: /register

sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix: /profile
  
sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /admin/resetting
_sonata_admin:
  resource: .
  type: sonata_admin
  prefix: /admin

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media
    
sonata_cache_cache:
    resource: '@SonataCacheBundle/Resources/config/routing/cache.xml'
    prefix: /
    
news:
    resource: '@SonataNewsBundle/Resources/config/routing/news.xml'
    prefix: /news